### ISSUE TITLE
Instance mask files

### ISSUE THREAD

**Issue by LeonardoViotti** [visipedia/iwildcam_comp#12]
Couldn't find `instance_masks/instance_masks/<ID>.png` in any of the download links. Both `train.zip` and `test.zip` contain only one folder with only `.jpg` extension files and `metadata.zip` only `.json` files. Maybe I'm missing something?

**Comment by stefanistrate** [comment]
I'm closing this issue for now since it was related to the 2021 competition. I believe the instance masks were only available on Kaggle, and not through the links mentioned in this repository.

However, we just launched [iWildCam 2022](https://www.kaggle.com/c/iwildcam2022-fgvc9) and we are providing MegaDetector v4 bounding boxes + DeepMAC instance masks on those bounding boxes. The data is available both on Kaggle and through direct links in the [Data Downloads](https://github.com/visipedia/iwildcam_comp/#data-downloads) section, and we invite you to give it a new chance and compete this year.
